# Generated by Django 3.2.5 on 2021-08-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='college_id',
            field=models.CharField(default='000000', max_length=50),
        ),
    ]
