# Generated by Django 3.2.5 on 2021-08-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainportal', '0002_student_college_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='college_id',
            field=models.CharField(max_length=50),
        ),
    ]
